# Generated by Django 3.0.5 on 2020-04-23 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='Workout',
            new_name='Name',
        ),
    ]
