# Generated by Django 3.0.5 on 2020-04-23 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20200423_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.Exercise'),
        ),
    ]
